# Attrition logistic regression

In [1]:
import pandas as pd

In [2]:
from sklearn import preprocessing

In [3]:
data_train=pd.read_csv("general_data.csv")

In [4]:
data_train

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4405,42,No,Travel_Rarely,Research & Development,5,4,Medical,1,4406,Female,...,3.0,Y,17,8,1,10.0,5,3,0,2
4406,29,No,Travel_Rarely,Research & Development,2,4,Medical,1,4407,Male,...,2.0,Y,15,8,0,10.0,2,3,0,2
4407,25,No,Travel_Rarely,Research & Development,25,2,Life Sciences,1,4408,Male,...,0.0,Y,20,8,0,5.0,4,4,1,2
4408,42,No,Travel_Rarely,Sales,18,2,Medical,1,4409,Male,...,0.0,Y,14,8,1,10.0,2,9,7,8
4409,40,No,Travel_Rarely,Research & Development,28,3,Medical,1,4410,Male,...,0.0,Y,12,8,0,NaN,6,21,3,9

In [5]:
data_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,4410.0,36.923810,9.133301,18.0,30.00,36.0,43.00,60.0
DistanceFromHome,4410.0,9.192517,8.105026,1.0,2.00,7.0,14.00,29.0
Education,4410.0,2.912925,1.023933,1.0,2.00,3.0,4.00,5.0
EmployeeCount,4410.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
EmployeeID,4410.0,2205.500000,1273.201673,1.0,1103.25,2205.5,3307.75,4410.0
JobLevel,4410.0,2.063946,1.106689,1.0,1.00,2.0,3.00,5.0
MonthlyIncome,4410.0,65029.312925,47068.888559,10090.0,29110.00,49190.0,83800.00,199990.0
NumCompaniesWorked,4391.0,2.694830,2.498887,0.0,1.00,2.0,4.00,9.0
PercentSalaryHike,4410.0,15.209524,3.659108,11.0,12.00,14.0,18.00,25.0
StandardHours,4410.0,8.000000,0.000000,8.0,8.00,8.0,8.00,8.0
StockOptionLevel,4410.0,0.793878,0.851883,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,4401.0,11.279936,7.782222,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,4410.0,2.799320,1.288978,0.0,2.00,3.0,3.00,6.0
YearsAtCompany,4410.0,7.008163,6.125135,0.0,3.00,5.0,9.00,40.0
YearsSinceLastPromotion,4410.0,2.187755,3.221699,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,4410.0,4.123129,3.567327,0.0,2.00,3.0,7.00,17.0

In [6]:
label_encoder=preprocessing.LabelEncoder()

In [7]:
data_train["Attrition"]=label_encoder.fit_transform(data_train["Attrition"])

In [8]:
data_train["BusinessTravel"]=label_encoder.fit_transform(data_train["BusinessTravel"])

In [9]:
data_train["EducationField"]=label_encoder.fit_transform(data_train["EducationField"])

In [10]:
data_train["Gender"]=label_encoder.fit_transform(data_train["Gender"])

In [11]:
data_train["Over18"]=label_encoder.fit_transform(data_train["Over18"])

In [12]:
data_train["Department"]=label_encoder.fit_transform(data_train["Department"])

In [13]:
data_train["JobRole"]=label_encoder.fit_transform(data_train["JobRole"])
data_train["MaritalStatus"]=label_encoder.fit_transform(data_train["MaritalStatus"])

In [14]:
data_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,4410.0,36.923810,9.133301,18.0,30.00,36.0,43.00,60.0
Attrition,4410.0,0.161224,0.367780,0.0,0.00,0.0,0.00,1.0
BusinessTravel,4410.0,1.607483,0.665304,0.0,1.00,2.0,2.00,2.0
Department,4410.0,1.260544,0.527673,0.0,1.00,1.0,2.00,2.0
DistanceFromHome,4410.0,9.192517,8.105026,1.0,2.00,7.0,14.00,29.0
Education,4410.0,2.912925,1.023933,1.0,2.00,3.0,4.00,5.0
EducationField,4410.0,2.247619,1.331067,0.0,1.00,2.0,3.00,5.0
EmployeeCount,4410.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
EmployeeID,4410.0,2205.500000,1273.201673,1.0,1103.25,2205.5,3307.75,4410.0
Gender,4410.0,0.600000,0.489954,0.0,0.00,1.0,1.00,1.0
JobLevel,4410.0,2.063946,1.106689,1.0,1.00,2.0,3.00,5.0
JobRole,4410.0,4.458503,2.461263,0.0,2.00,5.0,7.00,8.0
MaritalStatus,4410.0,1.097279,0.729955,0.0,1.00,1.0,2.00,2.0
MonthlyIncome,4410.0,65029.312925,47068.888559,10090.0,29110.00,49190.0,83800.00,199990.0
NumCompaniesWorked,4391.0,2.694830,2.498887,0.0,1.00,2.0,4.00,9.0
Over18,4410.0,0.000000,0.000000,0.0,0.00,0.0,0.00,0.0
PercentSalaryHike,4410.0,15.209524,3.659108,11.0,12.00,14.0,18.00,25.0
StandardHours,4410.0,8.000000,0.000000,8.0,8.00,8.0,8.00,8.0
StockOptionLevel,4410.0,0.793878,0.851883,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,4401.0,11.279936,7.782222,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,4410.0,2.799320,1.288978,0.0,2.00,3.0,3.00,6.0
YearsAtCompany,4410.0,7.008163,6.125135,0.0,3.00,5.0,9.00,40.0
YearsSinceLastPromotion,4410.0,2.187755,3.221699,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,4410.0,4.123129,3.567327,0.0,2.00,3.0,7.00,17.0

In [15]:
data_train.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeID                  0
Gender                      0
JobLevel                    0
JobRole                     0
MaritalStatus               0
MonthlyIncome               0
NumCompaniesWorked         19
Over18                      0
PercentSalaryHike           0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           9
TrainingTimesLastYear       0
YearsAtCompany              0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [16]:
data_train.corr()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,0.024751,-0.010846,0.006963,-0.035706,0.043194,NaN,0.008649,-0.039352,...,0.299243,NaN,-0.033137,NaN,-0.031753,0.680661,-0.027308,0.311309,0.216513,0.202089
Attrition,-0.159205,1.000000,0.000074,-0.048206,-0.009730,-0.015111,-0.057940,NaN,-0.004729,0.018125,...,0.042345,NaN,0.032533,NaN,-0.006839,-0.170338,-0.049431,-0.134392,-0.033019,-0.156199
BusinessTravel,0.024751,0.000074,1.000000,-0.010982,0.024616,0.002755,-0.015462,NaN,-0.002590,-0.039243,...,0.022401,NaN,-0.031054,NaN,0.003683,0.033997,-0.041888,-0.014575,-0.032591,-0.022636
Department,-0.010846,-0.048206,-0.010982,1.000000,0.012134,-0.004597,0.013720,NaN,-0.003455,0.003158,...,-0.003954,NaN,-0.007840,NaN,0.010512,-0.019839,0.012866,0.010078,0.014845,0.018016
DistanceFromHome,0.006963,-0.009730,0.024616,0.012134,1.000000,-0.008638,-0.024665,NaN,-0.001097,-0.044173,...,-0.013843,NaN,0.038125,NaN,0.011169,0.009374,-0.009001,0.031684,0.002290,0.021584
Education,-0.035706,-0.015111,0.002755,-0.004597,-0.008638,1.000000,0.012329,NaN,-0.009680,-0.016547,...,-0.016250,NaN,-0.040531,NaN,0.001261,-0.010717,0.010472,0.006080,0.022490,0.005358
EducationField,0.043194,-0.057940,-0.015462,0.013720,-0.024665,0.012329,1.000000,NaN,-0.000819,-0.005634,...,0.009023,NaN,-0.011214,NaN,0.021620,0.021593,-0.021793,0.023120,0.048181,0.021664
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeID,0.008649,-0.004729,-0.002590,-0.003455,-0.001097,-0.009680,-0.000819,NaN,1.000000,-0.013165,...,-0.001117,NaN,-0.004456,NaN,-0.014254,-0.001063,-0.010191,0.004086,0.000256,0.008579
Gender,-0.039352,0.018125,-0.039243,0.003158,-0.044173,-0.016547,-0.005634,NaN,-0.013165,1.000000,...,-0.066924,NaN,0.011841,NaN,0.019237,-0.027598,-0.030167,-0.017277,-0.021812,0.004438
JobLevel,-0.002884,-0.010290,0.046111,0.002923,-0.037329,0.045746,-0.019528,NaN,-0.003303,-0.026854,...,-0.009875,NaN,0.010973,NaN,0.000993,-0.036957,-0.032500,-0.064219,-0.060811,-0.055251
JobRole,0.011422,0.025809,-0.027194,-0.025466,-0.010293,0.030155,0.013106,NaN,0.005767,0.003724,...,-0.021841,NaN,-0.013465,NaN,0.023991,-0.012757,0.051744,-0.012886,-0.014635,0.010695
MaritalStatus,-0.095029,0.162070,0.024001,-0.044619,-0.027893,0.024991,-0.051409,NaN,0.001337,-0.009132,...,-0.037220,NaN,0.006378,NaN,0.014745,-0.077556,0.012798,-0.059986,-0.030915,-0.038570
MonthlyIncome,-0.044314,-0.031176,-0.037597,-0.032237,-0.021607,0.006410,0.008858,NaN,0.007338,0.007530,...,-0.020726,NaN,0.004325,NaN,0.026930,-0.033787,0.050112,0.000995,0.065219,0.024304
NumCompaniesWorked,0.299243,0.042345,0.022401,-0.003954,-0.013843,-0.016250,0.009023,NaN,-0.001117,-0.066924,...,1.000000,NaN,0.030860,NaN,0.017163,0.238807,-0.032286,-0.117959,-0.036656,-0.109667
Over18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PercentSalaryHike,-0.033137,0.032533,-0.031054,-0.007840,0.038125,-0.040531,-0.011214,NaN,-0.004456,0.011841,...,0.030860,NaN,1.000000,NaN,0.012548,-0.018736,-0.037392,-0.029707,-0.029542,-0.040864
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,-0.031753,-0.006839,0.003683,0.010512,0.011169,0.001261,0.021620,NaN,-0.014254,0.019237,...,0.017163,NaN,0.012548,NaN,1.000000,0.002694,-0.069902,0.007886,0.019063,0.017757
TotalWorkingYears,0.680661,-0.170338,0.033997,-0.019839,0.009374,-0.010717,0.021593,NaN,-0.001063,-0.027598,...,0.238807,NaN,-0.018736,NaN,0.002694,1.000000,-0.040762,0.627703,0.404444,0.458800
TrainingTimesLastYear,-0.027308,-0.049431,-0.041888,0.012866,-0.009001,0.010472,-0.021793,NaN,-0.010191,-0.030167,...,-0.032286,NaN,-0.037392,NaN,-0.069902,-0.040762,1.000000,-0.007894,0.016121,-0.013270
YearsAtCompany,0.311309,-0.134392,-0.014575,0.010078,0.031684,0.006080,0.023120,NaN,0.004086,-0.017277,...,-0.117959,NaN,-0.029707,NaN,0.007886,0.627703,-0.007894,1.000000,0.618409,0.769212
YearsSinceLastPromotion,0.216513,-0.033019,-0.032591,0.014845,0.002290,0.022490,0.048181,NaN,0.000256,-0.021812,...,-0.036656,NaN,-0.029542,NaN,0.019063,0.404444,0.016121,0.618409,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,-0.022636,0.018016,0.021584,0.005358,0.021664,NaN,0.008579,0.004438,...,-0.109667,NaN,-0.040864,NaN,0.017757,0.458800,-0.013270,0.769212,0.510224,1.000000

In [17]:
data_train.drop(['BusinessTravel', 'EducationField', 'EmployeeID', 'JobRole', 'EmployeeCount','TotalWorkingYears','NumCompaniesWorked', 'Over18', 'StandardHours'], axis=1, inplace=True)

In [18]:
data_train.corr()

,Age,Attrition,Department,DistanceFromHome,Education,Gender,JobLevel,MaritalStatus,MonthlyIncome,PercentSalaryHike,StockOptionLevel,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,-0.010846,0.006963,-0.035706,-0.039352,-0.002884,-0.095029,-0.044314,-0.033137,-0.031753,-0.027308,0.311309,0.216513,0.202089
Attrition,-0.159205,1.000000,-0.048206,-0.009730,-0.015111,0.018125,-0.010290,0.162070,-0.031176,0.032533,-0.006839,-0.049431,-0.134392,-0.033019,-0.156199
Department,-0.010846,-0.048206,1.000000,0.012134,-0.004597,0.003158,0.002923,-0.044619,-0.032237,-0.007840,0.010512,0.012866,0.010078,0.014845,0.018016
DistanceFromHome,0.006963,-0.009730,0.012134,1.000000,-0.008638,-0.044173,-0.037329,-0.027893,-0.021607,0.038125,0.011169,-0.009001,0.031684,0.002290,0.021584
Education,-0.035706,-0.015111,-0.004597,-0.008638,1.000000,-0.016547,0.045746,0.024991,0.006410,-0.040531,0.001261,0.010472,0.006080,0.022490,0.005358
Gender,-0.039352,0.018125,0.003158,-0.044173,-0.016547,1.000000,-0.026854,-0.009132,0.007530,0.011841,0.019237,-0.030167,-0.017277,-0.021812,0.004438
JobLevel,-0.002884,-0.010290,0.002923,-0.037329,0.045746,-0.026854,1.000000,-0.022021,0.047316,0.010973,0.000993,-0.032500,-0.064219,-0.060811,-0.055251
MaritalStatus,-0.095029,0.162070,-0.044619,-0.027893,0.024991,-0.009132,-0.022021,1.000000,-0.052383,0.006378,0.014745,0.012798,-0.059986,-0.030915,-0.038570
MonthlyIncome,-0.044314,-0.031176,-0.032237,-0.021607,0.006410,0.007530,0.047316,-0.052383,1.000000,0.004325,0.026930,0.050112,0.000995,0.065219,0.024304
PercentSalaryHike,-0.033137,0.032533,-0.007840,0.038125,-0.040531,0.011841,0.010973,0.006378,0.004325,1.000000,0.012548,-0.037392,-0.029707,-0.029542,-0.040864
StockOptionLevel,-0.031753,-0.006839,0.010512,0.011169,0.001261,0.019237,0.000993,0.014745,0.026930,0.012548,1.000000,-0.069902,0.007886,0.019063,0.017757
TrainingTimesLastYear,-0.027308,-0.049431,0.012866,-0.009001,0.010472,-0.030167,-0.032500,0.012798,0.050112,-0.037392,-0.069902,1.000000,-0.007894,0.016121,-0.013270
YearsAtCompany,0.311309,-0.134392,0.010078,0.031684,0.006080,-0.017277,-0.064219,-0.059986,0.000995,-0.029707,0.007886,-0.007894,1.000000,0.618409,0.769212
YearsSinceLastPromotion,0.216513,-0.033019,0.014845,0.002290,0.022490,-0.021812,-0.060811,-0.030915,0.065219,-0.029542,0.019063,0.016121,0.618409,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,0.018016,0.021584,0.005358,0.004438,-0.055251,-0.038570,0.024304,-0.040864,0.017757,-0.013270,0.769212,0.510224,1.000000

In [19]:
data_train.isna().sum()

Age                        0
Attrition                  0
Department                 0
DistanceFromHome           0
Education                  0
Gender                     0
JobLevel                   0
MaritalStatus              0
MonthlyIncome              0
PercentSalaryHike          0
StockOptionLevel           0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [21]:
data_train.columns

Index(['Age', 'Attrition', 'Department', 'DistanceFromHome', 'Education',
       'Gender', 'JobLevel', 'MaritalStatus', 'MonthlyIncome',
       'PercentSalaryHike', 'StockOptionLevel', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [20]:
y=data_train["Attrition"]

In [23]:
x=data_train[['Age', 'Department', 'DistanceFromHome', 'Education',
       'Gender', 'JobLevel', 'MaritalStatus', 'MonthlyIncome',
       'PercentSalaryHike', 'StockOptionLevel', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager']]

In [24]:
import statsmodels.api as sm

In [25]:
x1 = sm.add_constant(x)

In [26]:
Logistic = sm.Logit(y,x1)
Result = Logistic.fit()

Optimization terminated successfully.
         Current function value: 0.400372
         Iterations 7

In [27]:
Result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:              Attrition   No. Observations:                 4410
Model:                          Logit   Df Residuals:                     4395
Method:                           MLE   Df Model:                           14
Date:                Wed, 12 Aug 2020   Pseudo R-squ.:                 0.09355
Time:                        20:18:30   Log-Likelihood:                -1765.6
converged:                       True   LL-Null:                       -1947.9
Covariance Type:            nonrobust   LLR p-value:                 3.786e-69
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.3475      0.365      0.951      0.341      -0.368       1.064
Age                        -0.0408      0.005     -7.822      0.000      -0.051      -0.031
Department                 -0.2437      0.080     -3.034      0.002      -0.401      -0.086
DistanceFromHome           -0.0004      0.005     -0.076      0.940      -0.011       0.010
Education                  -0.0595      0.042     -1.418      0.156      -0.142       0.023
Gender                      0.0660      0.088      0.746      0.456      -0.107       0.239
JobLevel                   -0.0247      0.039     -0.628      0.530      -0.102       0.052
MaritalStatus               0.5827      0.063      9.316      0.000       0.460       0.705
MonthlyIncome           -1.973e-06   9.53e-07     -2.069      0.039   -3.84e-06   -1.04e-07
PercentSalaryHike           0.0151      0.012      1.298      0.194      -0.008       0.038
StockOptionLevel           -0.0651      0.051     -1.277      0.202      -0.165       0.035
TrainingTimesLastYear      -0.1379      0.035     -3.943      0.000      -0.207      -0.069
YearsAtCompany             -0.0362      0.016     -2.290      0.022      -0.067      -0.005
YearsSinceLastPromotion     0.1292      0.020      6.384      0.000       0.090       0.169
YearsWithCurrManager       -0.1367      0.022     -6.260      0.000      -0.179      -0.094
===========================================================================================
"""

# Inference

There is significance difference in monthly income which leads to attrition